name: intl
version: 0.15.6
author: Dart Team <misc@dartlang.org>
description: Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
homepage: https://github.com/dart-lang/intl
environment:
  sdk: '>=1.24.0 <2.0.0'
documentation: http://www.dartdocs.org/documentation/intl/latest
dependencies:
  path: '>=0.9.0 <2.0.0'
  html5: any
dependency_overrides:
  html5:
    path: ../html5
dev_dependencies:
  fixnum: '>=0.9.0 <0.11.0'
  test: '>=0.12.0 <0.13.0'
transformers:
- $dart2js:
    $exclude:
    - test/date_time_format_file_even_test.dart
    - test/date_time_format_file_odd_test.dart
    - test/find_default_locale_standalone_test.dart
